name: Push to GH Pages CI

on:
  pull_request_target:
    branches: [ main ]
    types: [ closed ]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: github-pages

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install and Build
      run: |
        npm i -g pnpm
        pnpm install
        pnpm run lint
        pnpm run build
    - name: Push to GitHub Pages
      # You may pin to the exact commit or the version.
      # uses: crazy-max/ghaction-github-pages@a117e4aa1fb4854d021546d2abdfac95be568a3a
      uses: crazy-max/ghaction-github-pages@v2.6.0
      with:
        build_dir: 'dist'
        author: "Petar Zarkov" # optional
        # Commit message
        commit_message: "Prod Build" # optional
        # Allow Jekyll to build your site
        jekyll: false # optional, default is true
        # If enabled, nothing will be pushed
        dry_run: false # optional, default is false
        # Enable verbose output
        verbose: true # optional, default is false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}